// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/rpc/code.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "google/rpc/Code.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CodeRoot

@implementation CodeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum Code

GPBEnumDescriptor *Code_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
  }
  return descriptor;
}

BOOL Code_IsValidValue(int32_t value__) {
  switch (value__) {
    case Code_Ok:
    case Code_Cancelled:
    case Code_Unknown:
    case Code_InvalidArgument:
    case Code_DeadlineExceeded:
    case Code_NotFound:
    case Code_AlreadyExists:
    case Code_PermissionDenied:
    case Code_Unauthenticated:
    case Code_ResourceExhausted:
    case Code_FailedPrecondition:
    case Code_Aborted:
    case Code_OutOfRange:
    case Code_Unimplemented:
    case Code_Internal:
    case Code_Unavailable:
    case Code_DataLoss:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
